"""
Seed-данные нормативов стоек регистрации (из реальной системы аэропорта).
"""

from datetime import date
from sqlalchemy.orm import Session

from app.models.checkin_norm import CheckinNorm

SEED_DATA = [
    {
        "name": "Inner",
        "zone": "internal",
        "priority": 1,
        "open_before_dep_min": 120,
        "close_before_dep_min": 40,
        "counters_count": 1,
        "has_business_counter": False,
        "business_counters_count": 0,
        "airline_codes": None,
        "aircraft_type_code": None,
        "airport_codes": None,
        "valid_from": date(2015, 1, 1),
    },
    {
        "name": "International",
        "zone": "international",
        "priority": 2,
        "open_before_dep_min": 120,
        "close_before_dep_min": 40,
        "counters_count": 2,
        "has_business_counter": False,
        "business_counters_count": 0,
        "airline_codes": None,
        "aircraft_type_code": None,
        "airport_codes": None,
        "valid_from": date(2015, 1, 1),
    },
    {
        "name": "Air China",
        "zone": "international",
        "priority": 1,
        "open_before_dep_min": 180,
        "close_before_dep_min": 40,
        "counters_count": 2,
        "has_business_counter": True,
        "business_counters_count": 0,
        "airline_codes": "CA",
        "aircraft_type_code": None,
        "airport_codes": None,
        "valid_from": date(2017, 6, 3),
    },
    {
        "name": "EY, TK, U2",
        "zone": "international",
        "priority": 1,
        "open_before_dep_min": 180,
        "close_before_dep_min": 40,
        "counters_count": 2,
        "has_business_counter": True,
        "business_counters_count": 1,
        "airline_codes": "EY,TK,HY",
        "aircraft_type_code": None,
        "airport_codes": None,
        "valid_from": date(2017, 6, 3),
    },
    {
        "name": "Белавиа",
        "zone": "international",
        "priority": 2,
        "open_before_dep_min": 120,
        "close_before_dep_min": 40,
        "counters_count": 3,
        "has_business_counter": True,
        "business_counters_count": 1,
        "airline_codes": "B2",
        "aircraft_type_code": None,
        "airport_codes": None,
        "valid_from": date(2019, 1, 29),
    },
    {
        "name": "FlyDubai",
        "zone": "international",
        "priority": 2,
        "open_before_dep_min": 120,
        "close_before_dep_min": 40,
        "counters_count": 3,
        "has_business_counter": True,
        "business_counters_count": 1,
        "airline_codes": "FZ",
        "aircraft_type_code": None,
        "airport_codes": None,
        "valid_from": date(2019, 9, 16),
    },
    {
        "name": "SouthWind",
        "zone": "international",
        "priority": 1,
        "open_before_dep_min": 120,
        "close_before_dep_min": 45,
        "counters_count": 2,
        "has_business_counter": False,
        "business_counters_count": 0,
        "airline_codes": None,
        "aircraft_type_code": None,
        "airport_codes": None,
        "valid_from": date(2024, 11, 28),
    },
    {
        "name": "Аэрофлот",
        "zone": "international",
        "priority": 1,
        "open_before_dep_min": 120,
        "close_before_dep_min": 40,
        "counters_count": 3,
        "has_business_counter": True,
        "business_counters_count": 1,
        "airline_codes": "SU",
        "aircraft_type_code": None,
        "airport_codes": None,
        "valid_from": date(2025, 6, 6),
    },
    {
        "name": "Победа",
        "zone": "international",
        "priority": 1,
        "open_before_dep_min": 120,
        "close_before_dep_min": 40,
        "counters_count": 3,
        "has_business_counter": True,
        "business_counters_count": 1,
        "airline_codes": "DP",
        "aircraft_type_code": None,
        "airport_codes": None,
        "valid_from": date(2025, 6, 6),
    },
    {
        "name": "Белавиа (Чартера)",
        "zone": "international",
        "priority": 1,
        "open_before_dep_min": 120,
        "close_before_dep_min": 40,
        "counters_count": 3,
        "has_business_counter": True,
        "business_counters_count": 0,
        "airline_codes": "B2",
        "aircraft_type_code": None,
        "airport_codes": "A9F,ADB,HRG,SSH,OBB,BEV,DCPS,SLL",
        "valid_from": date(2025, 9, 1),
    },
    {
        "name": "Белавиа (Баку/Тбилиси)",
        "zone": "international",
        "priority": 1,
        "open_before_dep_min": 120,
        "close_before_dep_min": 40,
        "counters_count": 3,
        "has_business_counter": True,
        "business_counters_count": 1,
        "airline_codes": "B2",
        "aircraft_type_code": None,
        "airport_codes": "TBS,GYD",
        "valid_from": date(2025, 10, 16),
    },
]


def seed_checkin_norms(db: Session) -> int:
    """Insert seed norms if the table is empty. Returns number of rows inserted."""
    existing = db.query(CheckinNorm).count()
    if existing > 0:
        return 0
    for row in SEED_DATA:
        db.add(CheckinNorm(**row, is_active=True))
    db.commit()
    return len(SEED_DATA)
